name: CI/CD Pipeline - Task Manager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v5

      # --- 1. BUILD & TEST BACKEND (Spring Boot) ---
      - name: ☕ Configurer Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ⚙️ Compiler et tester le Backend
        run: |
          cd backend
          mvn clean package -DskipTests

      # --- 2. BUILD FRONTEND (React) ---
      - name: 📦 Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ⚙️ Installer et builder le Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # --- 3. TEST DE CONTENEURISATION (Docker) ---
      - name: 🐳 Valider le build Docker Backend
        run: docker build -t task-backend:latest ./backend

      - name: 🐳 Valider le build Docker Frontend
        run: docker build -t task-frontend:latest ./frontend